#!/bin/sh


_path="/home/etud/Documents/temps_reel"

set -x

gnome-terminal -e "sh -c \"cd $_path/software/simulateur/dist/Debug/GNU-Linux/ && ./simulateur\"" 
gnome-terminal -e "sh -c \"cd $_path/software/monitor/monitor/ && ./monitor\""
cd $_path/software/raspberry/superviseur-robot/dist/Debug__PC_/GNU-Linux/ || exit 1;
sudo ./superviseur-robot

